apiVersion: v1
kind: Service
metadata:
  name: demo-api
  namespace: demo
  labels:
    app: demo-api
spec:
  type: NodePort
  selector:
    app: demo-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080